server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"

Spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: groovanoscode
    password: password
    hikari:
      connection-timeout: 600000
      maximum-pool-size: 50
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  main:
    web-application-type: servlet

