server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "health, info"

spring:
  datasource:
    url: jdbc:postgresql://awseb-e-bza2n8fru6-stack-awsebrdsdatabase-ihjxjscl7z9c.cbozedak9ijx.eu-central-1.rds.amazonaws.com:5432/ebdb
    username: groovanoscode
    password: password


  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true

  main:
    web-application-type: servlet